Update logistics.md
geo-smart/2023-hackweek-website pull request #29
Opened 2023-09-20 20:03 UTC by markweldensmith

The text below adds a Health & Safety section. Reviewed by Mark & Charley.

2023-09-20 21:03 UTC, scottyhq requested changes

2023-09-20 21:03 UTC, scottyhq commented on book/logistics.md
> +* Participants are expected to attend all scheduled activities. Contact [geohack@uw.edu](mailto:geohack@uw.edu)
```suggestion
* Participants are expected to attend all scheduled activities. Contact {{ contact_email }}
```

(the {{}} fields get filled automatically by the website build script and are set here  https://github.com/geo-smart/2023-hackweek-website/blob/main/book/_config.yml#L12

see: https://geosmart.hackweek.io/logistics.html

2023-09-22 16:05 UTC, aaarendt approved these changes

2023-09-22 16:12 UTC, aaarendt approved these changes

2023-09-22 16:13 UTC, merged